identity_providers:
    city_hall_issuer: saml2.ssc.c4.empleados
    citizen_issuer: saml2.ssc.c4
    onelogin:
        idp_homepage: https://sso-pre.santander.es/samlsso
        idp_entity_id: wso2.ssc
        idp_sso_target_url: https://sso-pre.santander.es/samlsso
        name_identifier_format: urn:oasis:names:tc:SAML:2.0:nameid-format:entityid
        assertion_consumer_service_binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
        force_authn: false
        idp_slo_target_url: https://sso-pre.santander.es/samlsso
        single_logout_service_binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect
        security:
            logout_requests_signed: true
            authn_requests_signed: true
            want_assertions_signed: true
            metadata_signed: true
            signature_method: http://www.w3.org/2000/09/xmldsig#rsa-sha1
            digest_method: http://www.w3.org/2000/09/xmldsig#sha1
            logout_responses_signed: true
